# Generated by Django 4.2.13 on 2024-06-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='intruder_image/default_error.png', upload_to='intruder_image/%Y/%m/%d/'),
        ),
    ]
